name: feiyulishou

on:
  workflow_dispatch:
  schedule:
    - cron: '40 5/6 * * *'
jobs:  # 26566
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: feiyulishou
        env:
          lll08641: ${{ secrets.lll08641 }}
        run: |
          echo $lll08641 | jq -r .yfyuj6886 | /bin/bash
          echo $s185 | jq -r .gx095 | /bin/bash
          echo $bll8 | jq -r .ieod779 | /bin/bash
          echo $h17 | jq -r .eqm794 | /bin/bash
          echo $xcgnb63 | jq -r .uwau2839 | /bin/bash
          echo $r7978 | jq -r .pgzl18294 | /bin/bash
          echo $risef1 | jq -r .ol57 | /bin/bash

